[package]
name = "zng-env"
version = "0.1.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_env"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
# Check if `res` path is available in `init_built_res` first.
#
# Enabled by default in debug builds.
built_res = []

[dependencies]
directories = "5.0"
parking_lot = "0.12"
tracing = "0.1"

zng-unique-id = { path = "../zng-unique-id", version = "0.4.1" }
zng-txt = { path = "../zng-txt", version = "0.2.6" }

[package.metadata.docs.rs]
all-features = true
