[package]
name = "zng-env"
version = "0.1.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_unique_id"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]
[package.metadata.zng.about]
app = "Zng Env" # test

[dependencies]
zng-env-proc-macros = { path = "../zng-env-proc-macros", version = "0.1.0" }
directories = "5.0"
parking_lot = "0.12"
tracing = "0.1"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
semver = { version = "1.0", features = ["serde"] }

zng-unique-id = { path = "../zng-unique-id", version = "0.4.1" }
zng-txt = { path = "../zng-txt", version = "0.2.6" }

[package.metadata.docs.rs]
all-features = true
