[package]
name = "zng-tp-licenses"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_third_party_licenses"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
# Include helpers for collecting third-party licenses.
build = ["dep:serde_json", "dep:deflate", "dep:bincode"]
# Include helpers for deserializing `build` encoded licenses.
bundle = ["dep:inflate", "dep:bincode"]

[dependencies]
zng-txt = { path = "../zng-txt", version = "0.2.3" }

serde = { version = "1.0", features = ["derive"] }

serde_json = { version = "1.0", optional = true }
deflate = { version = "*", optional = true }
inflate = { version = "*", optional = true }
bincode = { version = "1.3", optional = true }