[workspace]

resolver = "2"

members = [
    "crates/*",
    "examples",
    "examples/util",
    "tests",
    "tests/macro-tests",
]
default-members = ["crates/*"]

[profile.dev]
debug = 1

[profile.release-lto]
inherits = "release"
lto = "thin"

[profile.prebuild]
inherits = "release-lto"
