[package]
name = "zng-l10n-scraper"
version = "0.2.1"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_l10n_scraper"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
rayon = "1.10"
glob = "0.3"
rustc_lexer = "0.1"
clap = { version = "4.5", features = ["derive"] }
fluent-pseudo = "0.3"
