[package]
name = "calculator"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
zng = { path = "../../crates/zng", features = ["view_prebuilt"] }
mexprp = { version = "0.3", default-features = false }