[package]
name = "cargo-zng"
version = "0.2.2"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Zng project manager."
documentation = "https://zng-ui.github.io/doc/cargo_zng"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
# cli
clap = { version = "4.5", features = ["derive"] }
color-print = "0.3"

# l10n
rayon = "1.10"
glob = "0.3"
rustc_lexer = "0.1"
fluent-pseudo = "0.3"

# new
convert_case = "0.6"

# res
sha2 = "0.10"
parking_lot = "0.12"
walkdir = "2.5"
is_executable = "1.0"
anyhow = "1.0"
dunce = "1.0"
zng-env = { path = "../zng-env", version = "0.2.2" }

[package.metadata.docs.rs]
all-features = true
