[package]
name = "zng-view-api"
version = "0.2.4"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_view_api"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["ipc"]

# Enables creation of separate or pre-build view, enabled by default.
#
# When this is enabled communication with the view is (de)serialized which can add a 
# minor cost, something like a 1ms per 3MB frame request.
ipc = ["ipc-channel", "duct"]

# Implement `IntoVar<T>` for API types.
var = ["zng-var"]

# Include helpers for collecting third-party licenses.
third_party_collect = ["dep:serde_json", "dep:deflate"]
# Include helpers for deserializing `third_party_collect` encoded licenses.
third_party_bundle = ["dep:inflate"]

[dependencies]
euclid = { version = "0.22.6", features = [
    "serde",
    "bytemuck",
] } # same version as webrender, but with bytemuck

zng-unit = { path = "../zng-unit", version = "0.2.3" }
zng-txt = { path = "../zng-txt", version = "0.2.3" }
zng-var = { path = "../zng-var", version = "0.2.4", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
duct = { version = "0.13", optional = true }

tracing = "0.1"
flume = { version = "0.11", default-features = false }
num-traits = "0.2"
rustc-hash = "1.1"

bitflags = { version = "2.5", features = ["serde", "bytemuck"] }
bytemuck = { version = "1.15", features = ["derive"] }

ipc-channel = { version = "0.18", optional = true }
bincode = "1.3"
parking_lot = "0.12"
serde_variant = "0.1"

serde_json = { version = "1.0", optional = true }
deflate = { version = "*", optional = true }
inflate = { version = "*", optional = true }

unic-langid = { version = "0.9", features = ["serde"] }

[package.metadata.docs.rs]
all-features = true
