[package]
name = "zng-wgt-stack"
version = "0.2.2"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_stack"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]
debug_default = []
dyn_closure = []

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.2.2" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.2" }
zng-app = { path = "../zng-app", version = "0.2.2" }
zng-layout = { path = "../zng-layout", version = "0.2.2" }
zng-var = { path = "../zng-var", version = "0.2.2" }

euclid = "0.22"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
