[package]
name = "zng-wgt-inspector"
version = "0.2.3"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_inspector"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]
debug_default = []
live = []

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.2.2" }
zng-app = { path = "../zng-app", version = "0.2.2" }
zng-ext-input = { path = "../zng-ext-input", version = "0.2.2" }
zng-ext-font = { path = "../zng-ext-font", version = "0.2.3" }
zng-ext-config = { path = "../zng-ext-config", version = "0.2.2", default-features = false }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.2.2" }
zng-view-api = { path = "../zng-view-api", version = "0.2.2" }
zng-ext-window = { path = "../zng-ext-window", version = "0.2.2" }
zng-wgt-window = { path = "../zng-wgt-window", version = "0.2.3" }
zng-wgt-button = { path = "../zng-wgt-button", version = "0.2.3" }
zng-wgt-toggle = { path = "../zng-wgt-toggle", version = "0.2.3" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.2" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.2" }
zng-wgt-tooltip = { path = "../zng-wgt-tooltip", version = "0.2.3" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.2.3" }
zng-wgt-text-input = { path = "../zng-wgt-text-input", version = "0.2.3" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.2.2" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.2.2" }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.2.2" }
zng-wgt-stack = { path = "../zng-wgt-stack", version = "0.2.2" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.2" }
zng-wgt-wrap = { path = "../zng-wgt-wrap", version = "0.2.3" }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.2.2" }
zng-wgt-rule-line = { path = "../zng-wgt-rule-line", version = "0.2.3" }
zng-wgt-ansi-text = { path = "../zng-wgt-ansi-text", version = "0.2.3" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.2.2" }
zng-layout = { path = "../zng-layout", version = "0.2.2" }
zng-var = { path = "../zng-var", version = "0.2.2" }
zng-color = { path = "../zng-color", version = "0.2.2" }

serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
parking_lot = "0.12"
