[package]
name = "zng-wgt-grid"
version = "0.3.5"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_grid"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.4.0" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.17" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.17" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.2.17" }
zng-layout = { path = "../zng-layout", version = "0.2.13" }

tracing = "0.1"
