[package]
name = "zng-task"
version = "0.2.1"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_task"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
# Enables parking_lot deadlock detection.
deadlock_detection = ["parking_lot/deadlock_detection"]

# Enables http tasks.
http = [
    "serde",
    "serde_json",
    "isahc",
    "http-cache-semantics",
    "http-serde",
    "once_cell",
    "zng-txt",
    "async-recursion",
    "async-trait",
    "sha2",
    "base64",
    "fs4",
    "remove_dir_all",
]

# Enabled by doc tests.
test_util = []

[dependencies]
zng-task-proc-macros = { path = "../zng-task-proc-macros", version = "0.2.0" }
zng-clone-move = { path = "../zng-clone-move", version = "0.2.0" }
zng-unit = { path = "../zng-unit", version = "0.2.0" }
zng-app-context = { path = "../zng-app-context", version = "0.2.0" }
zng-time = { path = "../zng-time", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.1" }

zng-txt = { path = "../zng-txt", version = "0.2.0", optional = true }

tracing = "0.1"
pretty-type-name = "1"
flume = { version = "0.11", default-features = false, features = ["async"] }
rayon = "1"
blocking = "1"
parking_lot = "0.12"
futures-timer = "3"

isahc = { version = "1", features = ["cookies", "json"], optional = true }
futures-lite = "2"
async-fs = "2"
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
http-cache-semantics = { version = "1", optional = true }                  # isahc needs this version
http-serde = { version = "1", optional = true }
once_cell = { version = "1", optional = true }
async-recursion = { version = "1", optional = true }
async-trait = { version = "0.1", optional = true }
sha2 = { version = "0.10", optional = true }
base64 = { version = "0.22", optional = true }
fs4 = { version = "0.8", optional = true }
remove_dir_all = { version = "0.8", optional = true }
