name: CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always
  ZNG_TP_LICENSES: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo do version --verbose
      - run: cargo do fmt --check
      - run: cargo do check
      - run: cargo clean
  doc:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo do doc
      - run: cargo clean
  check-release:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --examples --tests --release
      - run: cargo clean
  test:
    runs-on: ubuntu-latest
    needs: [check]
    env:
      ZNG_TP_LICENSES: true
    steps:
    - name: install cargo-about
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-about
    - name: install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo do test --lib --bins --tests --nextest
    - run: cargo clean
  test-doc:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo do test --doc
      - run: cargo clean
  test-macro:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo do test --macro --all
      - run: cargo clean
  test-all:
    runs-on: ubuntu-latest
    needs: [check-release, doc, test, test-doc, test-macro]
    steps:
      - run: exit 0
