name: do

on:
  workflow_dispatch:
    inputs:
      runs-on: 
        default: 'ubuntu-latest'
      cmd:
      commit:

run-name: on ${{ github.event.inputs.runs-on }} do ${{ github.event.inputs.cmd }}

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always
  ZNG_TP_LICENSES: false

jobs:
  do:
    runs-on: ${{ github.event.inputs.runs-on }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: cargo do ${{ github.event.inputs.cmd }}
      - if: ${{ github.event.inputs.commit != '' }}
        run: |
          git add .
          git commit -m "${{ github.event.inputs.commit }}"
          git push
