name: do

on:
  workflow_dispatch:
    inputs:
      on: 
        default: 'ubuntu-latest'
        description: action runner
      do:
        description: do command
      commit:
        description: set to commit

run-name: on ${{ github.event.inputs.on }} do ${{ github.event.inputs.do }}

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always
  ZNG_TP_LICENSES: false

jobs:
  do:
    runs-on: ${{ github.event.inputs.on }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: cargo do ${{ github.event.inputs.do }}
      - if: ${{ github.event.inputs.commit != '' }}
        name: commit all changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add -A
          git commit -m "${{ github.event.inputs.commit }}"
          git push
