name: Nightly Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        feature: ['--all-features', '']
        profile: ['--release', '']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly check --workspace ${{ matrix.feature }} ${{ matrix.profile }} 
  check-os:
    needs: [check]
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        feature: ['--all-features', '']
        profile: ['--release', '']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly check --workspace ${{ matrix.feature }} ${{ matrix.profile }} 
  doc:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly doc --all-features --no-deps