name: Tag and Release

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always

jobs:
  check-ubuntu:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do version --verbose 
      - run: cargo do fmt --check
      - run: cargo check
      - run: cargo do clean # to print size
  check-windows:
    runs-on: windows-lastest
    env:
      CC: 'clang-cl'
      CXX: 'clang-cl'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do version --verbose 
      - run: cargo do fmt --check
      - run: cargo check
      - run: cargo do clean
  check-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do version --verbose 
      - run: cargo do fmt --check
      - run: cargo check
      - run: cargo do clean

  doc-ubuntu:
    runs-on: ubuntu-latest
    needs: ['check-ubuntu']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do doc
      - uses: actions/upload-artifact@v4
        with:
          name: doc
          path: target/doc
      - run: cargo clean

  prebuild-ubuntu:
    runs-on: ubuntu-latest
    needs: ['check-ubuntu']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do prebuild
      - uses: actions/upload-artifact@v4
        with:
          name: prebuilt-ubuntu
          path: zng-view-prebuilt/lib/libzng_view.so
      - run: cargo clean
  prebuild-windows:
    runs-on: windows-latest
    needs: ['check-windows']
    env:
      CC: 'clang-cl'
      CXX: 'clang-cl'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do prebuild
      - uses: actions/upload-artifact@v4
        with:
          name: prebuilt-windows
          path: zng-view-prebuilt/lib/lzng_view.dll
      - run: cargo clean
  prebuild-macos:
    runs-on: macos-13
    needs: ['check-macos']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do prebuild
      - uses: actions/upload-artifact@v4
        with:
          name: prebuilt-macos
          path: zng-view-prebuilt/lib/libzng_view.dylib
      - run: cargo clean

  test-ubuntu:
    runs-on: ubuntu-latest
    needs: ['prebuild-ubuntu']
    steps:
      - name: install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: install prebuilt
        uses: actions/download-artifact@v4
        with:
          name: prebuilt-ubuntu
          path: zng-view-prebuilt/lib
      - run: cargo to test --lib --bins --tests --nextest
      - run: cargo clean
      - run: cargo do test --doc
      - run: cargo clean
      - run: cargo do test --macro --all
      - run: cargo clean
  test-windows:
    runs-on: windows-latest
    needs: ['prebuild-ubuntu']
    env:
      CC: 'clang-cl'
      CXX: 'clang-cl'
      NEXTEST_RETRIES: 3
    steps:
      - name: install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: install prebuilt
        uses: actions/download-artifact@v4
        with:
          name: prebuilt-windows
          path: zng-view-prebuilt/lib
      - run: cargo to test --lib --bins --tests --nextest
      - run: cargo clean
      - run: cargo do test --doc
      - run: cargo clean
      - run: cargo do test --macro --all
      - run: cargo clean
  test-macos:
    runs-on: macos-13
    needs: ['prebuild-macos']
    env:
      NEXTEST_RETRIES: 3
    steps:
      - name: install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: install prebuilt
        uses: actions/download-artifact@v4
        with:
          name: prebuilt-macos
          path: zng-view-prebuilt/lib
      - run: cargo to test --lib --bins --tests --nextest
      - run: cargo clean
      - run: cargo do test --doc
      - run: cargo clean
      - run: cargo do test --macro --all
      - run: cargo clean

  test-cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do publish --test

  test-semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          shared-key: zng-semver-checks

  tag:
    runs-on: ubuntu-latest
    needs: [test-ubuntu, test-windows, test-macos, test-cargo-publish, test-semver-checks]
    permissions:
      contents: write
    outputs:
      tag_name: ${{ steps.publish_version_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release
      - id: publish_version_tag
        run: cargo do publish_version_tag --execute | tail -n 1 >> "$GITHUB_OUTPUT"
  
  publish-release:
    runs-on: ubuntu-latest
    needs: [tag]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: prebuilt-ubuntu
          path: prebuilt
      - uses: actions/download-artifact@v4
        with:
          name: prebuilt-windows
          path: prebuilt
      - uses: actions/download-artifact@v4
        with:
          name: prebuilt-macos
          path: prebuilt
      - run: ls --all ./prebuilt
      - name: publish release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.tag_name }}
          artifacts: "prebuilt/*"

  publish-doc:
    runs-on: ubuntu-latest
    needs: [tag]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: zng-ui/zng-ui.github.io
          ref: main
          token:  ${{ secrets.PAGES_DOC_PUSH_TOKEN }}

      - run: rm -rf doc
      - uses: actions/download-artifact@v4
        name: push
        with:
          name: doc
          path: doc
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add -A
          git commit -m ${{ needs.tag.outputs.tag_name }} --quiet
          git push

  publish-crates:
    runs-on: ubuntu-latest
    needs: [publish-release, publish-doc]
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: cargo do publish --execute ${{ github.run_attempt > 1 && '--no-burst' || '' }}

  cleanup:
    runs-on: ubuntu-latest
    if: always()
    needs: [publish-release, publish-doc]
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            prebuilt-*
            doc
          failOnError: false