name: Find Breaking Changes

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ZNG_TP_LICENSES: false

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: install cargo-semver-checks
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-semver-checks
      - uses: actions/checkout@v4
      - run: cargo do semver_check