name: Test Prebuild Avif

on:
  workflow_dispatch:
  push:
    branches: [ "avif-prebuild" ]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - name: build dav1d
        env:
          DAV1D_DIR: dav1d_dir
          LIB_PATH: lib/x86_64-linux-gnu
        run: |
          pip install -U pip
          pip install -U wheel setuptools
          pip install -U meson ninja
          git clone --branch 1.3.0 --depth 1 https://code.videolan.org/videolan/dav1d.git
          cd dav1d
          meson build -Dprefix=$HOME/$DAV1D_DIR -Denable_tools=false -Denable_examples=false --buildtype release
          ninja -C build
          ninja -C build install
          echo "PKG_CONFIG_PATH=$HOME/$DAV1D_DIR/$LIB_PATH/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$HOME/$DAV1D_DIR/$LIB_PATH" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - run: cargo do comment_feature -u "zng-view/Cargo.toml" avif
      - run: cargo do prebuild --features avif
      - run: cargo clean
      - run: cargo do comment_feature "zng-view/Cargo.toml" avif
      - name: upload prebuild
        uses: actions/upload-artifact@v4
        with:
          name: prebuilt-ubuntu
          path: zng-view-prebuilt/lib/libzng_view.so